version: '2.1'

volumes:
  redis-data: {}
  openvas-var-lib: {}
  gvm-var-lib: {}
  postgres-data: {}
  run-redis: {}
  run-ospd: {}
  run-gvm: {}

services:
  gvm-postgres:
    image: admirito/gvm-postgres:20
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: gvmd
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: gvmduser
    volumes:
      - postgres-data:/var/lib/postgresql/data

  gvmd:
    # CONNECTED /run/ospd/ospd.sock
    image: admirito/gvmd:20
    environment:
      GVMD_POSTGRESQL_URI: postgresql://gvmduser:mypassword@gvm-postgres:5432/gvmd?application_name=gvmd
    volumes:
      - openvas-var-lib:/var/lib/openvas
      - gvm-var-lib:/var/lib/gvm
      - run-redis:/run/redis
      - run-ospd:/run/ospd
      - run-gvm:/run/gvm
    depends_on:
      gvm-postgres:
        condition: service_started

  gsad:
    image: admirito/gsad:20
    volumes:
      - run-gvm:/run/gvm
    ports:
      - 8080:80
    
    environment:
      GVMD_HOST: gvmd
      GVMD_PORT: '9390'

    depends_on:
      gvmd:
        condition: service_started

  openvas:
    # LISTENING /run/ospd/ospd.sock
    # CONNECTED /run/redis/redis.sock
    image: admirito/openvas:20
    privileged: true
    sysctls:
      net.core.somaxconn: '2048'
    volumes:
      - openvas-var-lib:/var/lib/openvas
      - run-redis:/run/redis
      - run-ospd:/run/ospd

    depends_on:
      gvm-postgres:
        condition: service_started

  # It is recommended to add vm.overcommit_memory=1 into
  # /etc/systcl.conf on the host
  redis:
    # LISTENING /run/redis/redis.sock
    image: redis:5.0
    volumes:
    - run-redis:/run/redis
    - redis-data:/data
    command: redis-server --port 0 --unixsocket /run/redis/redis.sock --unixsocketperm 755 --databases 1025
    privileged: true
    sysctls:
      net.core.somaxconn: '2048'

    depends_on:
      openvas:
        condition: service_started
