{{- if .Values.ingress.enabled -}}
{{- $fullName := include "gvm.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "gvm.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

spec:
  rules:
    - host: {{ .Values.ingress.hostname | quote }}
      http:
        paths:
          - backend:
              service:
                name: {{ $fullName }}
                port:
                  name: http
            path: /
            pathType: ImplementationSpecific


  {{- if .Values.ingress.tls }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname | quote }}
      secretName: {{ .Values.ingress.secretName }}
    {{- end }}
  {{- end }}
{{- end }}
